### ISSUE TITLE
Status bar issue

### ISSUE THREAD

**Issue by TheBiotechScientist** [alefragnani/atom-code-dark-ui#3]
Hi, I have recently **updated** my **Atom** editor to **1.60.0**, but I notice that (_when I restarted the editor_) the **status bar** was over the "default" bar. It may be an issue about a changed position in the new version of the editor, I think.

When I'm in the **Settings** tab, some part of the status bar disappear:
![image](https://user-images.githubusercontent.com/39642010/193377188-fce0d292-e443-4a8a-b764-154a35b914dd.png)

And in file tab:
![image](https://user-images.githubusercontent.com/39642010/193377209-ce493e7f-5c93-45ba-83fc-73aaa85c4522.png)

I'm using Windows 10
When executing in terminal the command `>apm --version` I get:
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.60.0
python 3.7.11
git 2.30.1.windows.1
visual studio 2015

I hope this issue can be solved, this is a great theme!!

Thanks a lot.

**Comment by alefragnani** [comment]
Hi @TheBiotechScientist ,

It’s been a while I don’t use Atom, neither have it installed on my main machine now to verify the issue. But, based on your description, I wonder if this is an issue in this theme, or Atom itself. 

Could you please confirm that this issue doesn’t happen on the _built-in_ themes? 

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 

Thanks for your understanding
